### ISSUE TITLE
Is this free to use?

### ISSUE THREAD

**Issue by Matty91722** [alexemanuelol/Discord-BOT-Battlemetrics-Ban-Notifier#3]
Hello, 
Not to sure about how I contact you so here I am. Is this open source or do I need permission to use this?

**Comment by alexemanuelol** [comment]
Ofcourse it's free to use, otherwise I wouldn't habe published it here 😂

**Comment by Matty91722** [comment]
Cool, new to all this. Thanks bud 👍
